---
_extends: .github:common-settings.yaml

repository:
  name: .github
  description: Template repository for a .github repository
  topics: template, github, repository, settings
  is_template: true

branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts: ['Create Renovate Changeset', 'Lint', 'Release', 'Renovate']
      enforce_admins: true
      required_pull_request_reviews: null
      restrictions: null
      required_linear_history: true
