---
_extends: .github:common-settings.yaml

repository:
  name: .github
  description: Template repository for a .github repository
  topics: template, github, repository, settings
  is_template: true

branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts:
          - Advanced Security Analysis
          - CodeQL
          - Container Scan
          - Create Renovate Changeset
          - GitGuardian Scan
          - License Scan
          - Prepare Repository List
          - Quality Check
          - Release
          - Renovate
          - Review Dependencies
          - Triage

      enforce_admins: true
      required_pull_request_reviews:
        dismiss_stale_reviews: true
        require_code_owner_reviews: false
        required_approving_review_count: 0
      restrictions: null
      required_linear_history: true
