bracketSpacing: false
printWidth: 120
singleQuote: true
tabWidth: 2
overrides:
  - files:
      - '.changeset/*.md'
    options:
      singleQuote: false
  - files:
      - '.vscode/*.json'
    options:
      tabWidth: 4
