autoInstallPeers: true

ignoreWorkspaceRootCheck: true

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver

packages:
  - .
  - .github/actions/*

savePrefix: ''

shamefullyHoist: true

shellEmulator: true

strictPeerDependencies: false
