import type {Octokit} from '@octokit/rest'
import type {CategorizationInfo, MultiPackageInfo, ReleaseEntry} from './changeset-info-formatter'
import * as core from '@actions/core'
import {appendSharedChangesetSections} from './changeset-info-formatter'

export async function createPRComment(
  octokit: Octokit,
  owner: string,
  repo: string,
  prNumber: number,
  changesetContent: string,
  releases: ReleaseEntry[],
  changesetPath: string,
  dependencies: string[],
  categorizationResult: CategorizationInfo,
  multiPackageResult: MultiPackageInfo,
): Promise<void> {
  try {
    const sections: string[] = [
      '## 🔄 Changeset Generated',
      '',
      `📁 **Location**: \`.changeset/${changesetPath}\``,
      '',
    ]

    sections.push('### 📝 Summary')
    sections.push('```')
    sections.push(changesetContent)
    sections.push('```')
    sections.push('')

    appendSharedChangesetSections(
      sections,
      dependencies,
      releases,
      categorizationResult,
      multiPackageResult,
    )

    sections.push('### ℹ️ Information')
    sections.push(
      '- This changeset was automatically generated by the enhanced Renovate-Changesets action',
    )
    sections.push('- The changeset will be used to determine the next version bump when merging')
    sections.push(
      '- Review the changeset content above to ensure it accurately describes the changes',
    )

    const comment = sections.join('\n')

    await octokit.rest.issues.createComment({
      owner,
      repo,
      issue_number: prNumber,
      body: comment,
    })

    core.info(`Created enhanced PR comment with detailed changeset information on PR #${prNumber}`)
  } catch (error) {
    core.warning(
      `Failed to create PR comment: ${error instanceof Error ? error.message : String(error)}`,
    )
    throw error
  }
}
