---
name: Renovate Changesets
description: Generate changeset files for Renovate dependency updates
author: bfra.me
branding:
  icon: edit-3
  color: blue

inputs:
  branch-prefix:
    description: Branch prefix that Renovate was configured with (defaults to 'renovate/')
    required: false
    default: renovate/
  comment-pr:
    description: Post a comment on the PR with changeset details
    required: false
    default: 'false'
  update-pr-description:
    description: Update the PR description with changeset information
    required: false
    default: 'false'
  commit-back:
    description: Automatically commit changeset files back to the Renovate branch
    required: false
    default: 'false'
  commit-message-template:
    description: Template for commit messages (supports {{count}}, {{files}}, {{file}} placeholders)
    required: false
    default: 'chore: add changeset for renovate updates\n\nAdded {{count}} changeset file(s): {{files}}'
  config-file:
    description: Path to configuration file (JSON or YAML)
    required: false
  config:
    description: Inline configuration (JSON/YAML)
    required: false
  default-changeset-type:
    description: Default changeset type when no specific configuration matches (patch, minor, major)
    required: false
    default: patch
  exclude-patterns:
    description: File patterns to exclude from changeset generation (comma-separated)
    required: false
  skip-branch-prefix-check:
    description: Skip checking that the branch ref begins with branch-prefix
    required: false
    default: 'false'
  sort:
    description: Sort dependency bumps and update messages within changesets
    required: false
    default: 'false'
  token:
    description: GitHub token for API access
    required: false
    default: ${{ github.token }}
  working-directory:
    description: Working directory
    required: false
    default: .
  # TASK-032: Merge conflict handling inputs
  auto-resolve-conflicts:
    description: Automatically resolve merge conflicts when possible
    required: false
    default: 'true'
  max-retries:
    description: Maximum number of retry attempts for git operations (0-10)
    required: false
    default: '3'
  retry-delay:
    description: Initial retry delay in milliseconds (100-10000)
    required: false
    default: '1000'
  # TASK-034: Grouped PR update inputs
  update-grouped-prs:
    description: Enable updating multiple PRs in grouped updates
    required: false
    default: 'false'
  max-grouped-prs:
    description: Maximum number of PRs to update in a group (1-50)
    required: false
    default: '10'
  grouped-pr-failure-strategy:
    description: How to handle failures in grouped updates (continue, stop)
    required: false
    default: continue
  skip-current-pr-in-group:
    description: Skip updating the current PR when updating grouped PRs to avoid duplicates
    required: false
    default: 'true'

outputs:
  changesets-created:
    description: Number of changesets created
  changeset-files:
    description: List of created changeset files (JSON array)
  update-type:
    description: Detected update type (npm, github-actions, docker, etc.)
  dependencies:
    description: List of detected dependencies (JSON array)
  changeset-summary:
    description: Summary of the changeset content
  # TASK-020: Enhanced categorization outputs
  primary-category:
    description: Primary update category (major, minor, patch, security)
  all-categories:
    description: All update categories present (JSON array)
  categorization-summary:
    description: Detailed categorization summary (JSON object)
  security-updates:
    description: Number of security-related updates
  breaking-changes:
    description: Number of dependencies with breaking changes
  high-priority-updates:
    description: Number of high-priority updates
  average-risk-level:
    description: Average risk level (0-100 scale)
  categorization-confidence:
    description: Confidence in categorization (high, medium, low)
  # TASK-024: Multi-package analysis outputs
  multi-package-strategy:
    description: Strategy used for changeset generation (single, multiple, grouped)
  workspace-packages-count:
    description: Number of packages detected in the workspace
  package-relationships-count:
    description: Number of package relationships analyzed
  affected-packages:
    description: List of packages affected by the update (JSON array)
  multi-package-reasoning:
    description: Reasoning chain for multi-package decisions (JSON array)
  # TASK-028/029: Git operations outputs
  commit-success:
    description: Whether changeset files were successfully committed back to the branch
  commit-sha:
    description: SHA of the commit containing changeset files (if committed)
  committed-files:
    description: List of committed changeset files (JSON array)
  git-error:
    description: Error message if git operations failed
  # TASK-030: Push operations outputs
  push-success:
    description: Whether changeset files were successfully pushed to the remote branch
  push-error:
    description: Error message if push operations failed
  # TASK-032: Merge conflict handling outputs
  conflicts-resolved:
    description: Whether merge conflicts were encountered and resolved automatically
  conflict-resolution:
    description: Details about the conflict resolution strategy used
  branch-updated:
    description: Whether the remote branch was updated during the operation
  retry-attempts:
    description: Number of retry attempts made for git operations
  # TASK-031/033: PR management outputs
  pr-description-updated:
    description: Whether the PR description was successfully updated with changeset information
  pr-description-error:
    description: Error message if PR description update failed
  pr-comment-created:
    description: Whether a comment was successfully posted to the PR with changeset details
  pr-comment-error:
    description: Error message if PR comment creation failed
  # TASK-034: Grouped PR update outputs
  grouped-prs-enabled:
    description: Whether grouped PR updates were enabled
  grouped-prs-found:
    description: Number of PRs found in the group
  grouped-prs-updated:
    description: Number of PRs successfully updated in the group
  grouped-prs-failed:
    description: Number of PRs that failed to update in the group
  grouped-pr-strategy:
    description: Strategy used for grouping PRs (none, branch-pattern, group-name, dependencies)
  grouped-pr-identifier:
    description: Identifier for the group (group name or common prefix)
  grouped-pr-results:
    description: Detailed results for each PR operation (JSON array)

runs:
  using: node20
  main: dist/index.js
