# Apply repository settings defined in .github/settings.yml.
---
name: Apply Repository Settings

on:
  push:
    branches: [$default-branch]
    paths:
      - '.github/settings.yml'
      - '.github/workflows/apply-repo-settings.yaml'
  schedule:
    - cron: $cron-daily
  workflow_dispatch:

permissions: {}

jobs:
  apply-repo-settings:
    runs-on: ubuntu-latest
    steps:
      - name: Get Workflow Access Token
        id: get-workflow-access-token
        uses: peter-murray/workflow-application-token-action@8e1ba3bf1619726336414f1014e37f17fbadf1db # v2.1.0
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
          organization: ${{ github.repository_owner }}
          permissions: 'administration:write, contents:read, issues:write, members:write'

      - name: Apply Repository Settings And ${{ github.repository_owner }}/.github Defaults
        uses: exivity/actions/sync-defaults@bed05a649380cafbcad19dbb856be49ef7c61c88 # main
        with:
          gh-token: ${{ steps.get-workflow-access-token.outputs.token }}
