---
# Create changesets for Renovate dependency updates.
name: Renovate Changesets

on:
  merge_group:
  pull_request_target:

permissions:
  contents: read

jobs:
  renovate-changesets:
    if: github.actor == 'renovate[bot]' || github.actor == 'bfra-me[bot]'
    name: Renovate Changesets
    secrets: inherit
    uses: bfra-me/.github/.github/workflows/renovate-changeset.yaml@6c0d1fb3a14317846304c39a0454caf285dbce20 # v4.14.0
