---
# Create changesets for Renovate dependency updates.
name: Renovate Changesets

on:
  merge_group:
  pull_request_target:

permissions:
  contents: read

jobs:
  renovate-changesets:
    if: github.actor == 'renovate[bot]' || github.actor == 'bfra-me[bot]'
    name: Renovate Changesets
    secrets: inherit
    uses: bfra-me/.github/.github/workflows/renovate-changeset.yaml@bbf77bc2c8fc161b3a6b45f78c48ac7e1756256c # v4.16.32
