# Update repository settings to match the definitions in .github/settings.yml.
---
name: Update Repo Settings

on:
  push:
    branches: [$default-branch]
  schedule:
    - cron: $cron-daily
  workflow_dispatch:

jobs:
  update-repo-settings:
    name: Update Repo Settings
    secrets: inherit
    uses: bfra-me/.github/.github/workflows/update-repo-settings.yaml@5fc9776c379f20bfdee2c8982699faf8f0059f29 # v4.16.36
