# Update repository settings to match the definitions in .github/settings.yml.
---
name: Update Repo Settings

on:
  push:
    branches: [$default-branch]
  schedule:
    - cron: $cron-daily
  workflow_dispatch:

jobs:
  update-repo-settings:
    name: Update Repo Settings
    secrets: inherit
    uses: bfra-me/.github/.github/workflows/update-repo-settings.yaml@c18397a0adf7a17819e34595e2d499166d252dd5 # v2.0.6
