import {spawnSync} from 'node:child_process'
import {promises as fs} from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import process from 'node:process'
import {fileURLToPath} from 'node:url'
import {afterEach, beforeEach, describe, expect, it} from 'vitest'
import {run} from '../../src/run.js'
import {authoredReleases, effectiveReleases, runChangesetsOracle} from './changesets-oracle.js'
import {getContractState, getOctokitMocks} from './setup.js'

// Package versions in this fixture are a deliberate snapshot of the repository as PR #2585 saw
// it, not a mirror of current versions. Attribution matches on package name, so they never need
// bumping after a release.
const fixtureRoot = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  'fixtures/bfra-github',
)
const lockfileMaintenanceBody = `This PR contains the following updates:

| Update | Change |
|---|---|
| lockFileMaintenance | All lock files updated (every Monday before 3 AM) |

---

> [!WARNING]
> Some dependencies could not be looked up. Check the [Dependency Dashboard](../issues/7) for more information.

🔧 This Pull Request updates lock files to use the latest dependency versions.

---

### Configuration

📅 **Schedule**: (in timezone America/Phoenix)

- Branch creation
  - "before 3am on Monday"
- Automerge
  - At any time (no schedule defined)

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR is behind base branch, or you tick the rebase/retry checkbox.

👻 **Immortal**: This PR will be recreated if closed unmerged. Get [config help](https://redirect.github.com/renovatebot/renovate/discussions) if that's undesired.

---

  - [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check this box

---

This PR has been generated by [Mend Renovate CLI](https://redirect.github.com/renovatebot/renovate).
<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiI0NC4zMC4wIiwidXBkYXRlZEluVmVyIjoiNDQuMzAuMCIsInRhcmdldEJyYW5jaCI6Im1haW4iLCJsYWJlbHMiOlsiYXV0b21lcmdlIiwiZGVwZW5kZW5jaWVzIiwiamF2YXNjcmlwdE1haW50ZW5hbmNlIiwicmVub3ZhdGUiLCJzY2hlZHVsZWQiXX0==-->`

let workspace = ''
const contractState = getContractState()
const octokitMocks = getOctokitMocks()

describe('lockfile maintenance contract', () => {
  beforeEach(async () => {
    workspace = await fs.mkdtemp(path.join(os.tmpdir(), 'renovate-changesets-lockfile-'))
    await fs.cp(fixtureRoot, workspace, {recursive: true})
    initializeGitRepository(workspace)
    process.env.NODE_ENV = 'production'
    delete process.env.VITEST
    process.env.GITHUB_EVENT_NAME = 'pull_request_target'
    process.env.GITHUB_EVENT_PATH = path.join(workspace, 'event.json')
    process.env.GITHUB_REPOSITORY = 'bfra-me/.github'
    process.env.GITHUB_WORKSPACE = workspace
    process.env.GITHUB_TOKEN = 'contract-token'
    delete process.env.BRANCH_PREFIX
    delete process.env.SKIP_BRANCH_CHECK
    delete process.env.SORT_CHANGESETS
    delete process.env.TARGET_PACKAGE

    await fs.writeFile(
      process.env.GITHUB_EVENT_PATH,
      JSON.stringify({
        pull_request: {
          number: 2585,
          title: 'chore(deps): maintain lockfiles',
          body: lockfileMaintenanceBody,
          user: {login: 'renovate[bot]'},
          labels: [{name: 'dependencies'}, {name: 'renovate'}],
          head: {ref: 'renovate/lock-file-maintenance'},
        },
      }),
      'utf8',
    )

    contractState.inputs = {
      token: 'contract-token',
      'working-directory': workspace,
      'branch-prefix': 'renovate/',
      'config-file': '',
      config: '',
      'default-changeset-type': 'patch',
      'exclude-patterns': '',
      'target-package': '',
      'commit-message-template': 'chore: add changeset for renovate updates',
      'max-retries': '0',
      'retry-delay': '100',
      'max-grouped-prs': '10',
      'grouped-pr-failure-strategy': 'continue',
    }
    contractState.booleanInputs = {
      'skip-branch-prefix-check': false,
      sort: false,
      emoji: false,
      'comment-pr': false,
      'update-pr-description': false,
      'commit-back': false,
      'auto-resolve-conflicts': true,
      'update-grouped-prs': false,
      'skip-current-pr-in-group': true,
    }
    octokitMocks.listFiles.mockResolvedValue({
      data: [
        {filename: 'pnpm-lock.yaml', status: 'modified', additions: 1, deletions: 1},
        {
          filename: '.github/actions/renovate-changesets/dist/index.js',
          status: 'modified',
          additions: 1,
          deletions: 1,
        },
        {
          filename: '.github/actions/update-metadata/dist/index.js',
          status: 'modified',
          additions: 1,
          deletions: 1,
        },
        {
          filename: '.github/actions/update-repository-settings/dist/index.js',
          status: 'modified',
          additions: 1,
          deletions: 1,
        },
      ],
    })
    octokitMocks.listCommits.mockResolvedValue({data: []})
  })

  afterEach(async () => {
    if (workspace.length > 0) await fs.rm(workspace, {recursive: true, force: true})
    workspace = ''
  })

  it('attributes lockfile maintenance to every changed workspace package', async () => {
    await run()

    expect(contractState.failed).toEqual([])
    expect(contractState.outputs.get('changeset-summary')).toBe(
      'Refresh pnpm lockfile dependencies',
    )
    expect(contractState.outputs.get('update-type')).toBe('lockfile-maintenance')
    expect(JSON.parse(contractState.outputs.get('dependencies') ?? 'null')).toEqual([])

    const oracle = await runChangesetsOracle('lockfile-maintenance', workspace, {
      errors: contractState.errors,
      warnings: contractState.warnings,
      outputs: contractState.outputs,
    })
    expect(authoredReleases(oracle.releasePlan).map(({name, type}) => ({name, type}))).toEqual([
      {name: '@bfra.me/.github', type: 'patch'},
      {name: 'renovate-changesets', type: 'patch'},
      {name: 'update-metadata', type: 'patch'},
      {name: 'update-repository-settings', type: 'patch'},
    ])
    expect(effectiveReleases(oracle.releasePlan).map(({name, type}) => ({name, type}))).toEqual([
      {name: '@bfra.me/.github', type: 'patch'},
      {name: 'renovate-changesets', type: 'patch'},
      {name: 'update-metadata', type: 'patch'},
      {name: 'update-repository-settings', type: 'patch'},
    ])
    const summaries = oracle.releasePlan.changesets.map(changeset => changeset.summary)
    expect(summaries).toHaveLength(4)
    expect(summaries.every(summary => summary.includes('Refresh pnpm lockfile dependencies'))).toBe(
      true,
    )
  })

  it('does not suppress an unrelated pending changeset', async () => {
    await fs.writeFile(
      path.join(workspace, '.changeset/existing-renovate-changesets.md'),
      `---\n'renovate-changesets': patch\n---\n\nExisting pending work.\n`,
      'utf8',
    )

    await run()

    expect(contractState.outputs.get('changesets-created')).toBe('4')
    expect(JSON.parse(contractState.outputs.get('changeset-files') ?? 'null')).toHaveLength(4)

    // Remove the seeded file before invoking the oracle: Changesets status reports every file in
    // .changeset, while the action's changeset-files output identifies what this run authored.
    await fs.rm(path.join(workspace, '.changeset/existing-renovate-changesets.md'))

    const oracle = await runChangesetsOracle('lockfile-maintenance-existing', workspace, {
      errors: contractState.errors,
      warnings: contractState.warnings,
      outputs: contractState.outputs,
    })
    expect(authoredReleases(oracle.releasePlan).map(({name, type}) => ({name, type}))).toEqual([
      {name: '@bfra.me/.github', type: 'patch'},
      {name: 'renovate-changesets', type: 'patch'},
      {name: 'update-metadata', type: 'patch'},
      {name: 'update-repository-settings', type: 'patch'},
    ])
    expect(effectiveReleases(oracle.releasePlan).map(({name, type}) => ({name, type}))).toEqual([
      {name: '@bfra.me/.github', type: 'patch'},
      {name: 'renovate-changesets', type: 'patch'},
      {name: 'update-metadata', type: 'patch'},
      {name: 'update-repository-settings', type: 'patch'},
    ])
    expect(oracle.releasePlan.changesets).toHaveLength(4)
  })

  it('does not suppress a changeset inherited from main', async () => {
    await fs.writeFile(
      path.join(workspace, '.changeset/existing-renovate-changesets.md'),
      `---\n'renovate-changesets': patch\n---\n\nRefresh pnpm lockfile dependencies\n\n**Multi-package update** for package \`renovate-changesets\`.\n`,
      'utf8',
    )

    await run()

    expect(contractState.outputs.get('changesets-created')).toBe('4')
    expect(JSON.parse(contractState.outputs.get('changeset-files') ?? 'null')).toHaveLength(4)

    await fs.rm(path.join(workspace, '.changeset/existing-renovate-changesets.md'))

    const oracle = await runChangesetsOracle('lockfile-maintenance-identical', workspace, {
      errors: contractState.errors,
      warnings: contractState.warnings,
      outputs: contractState.outputs,
    })
    expect(authoredReleases(oracle.releasePlan).map(({name, type}) => ({name, type}))).toEqual([
      {name: '@bfra.me/.github', type: 'patch'},
      {name: 'renovate-changesets', type: 'patch'},
      {name: 'update-metadata', type: 'patch'},
      {name: 'update-repository-settings', type: 'patch'},
    ])
    expect(effectiveReleases(oracle.releasePlan).map(({name, type}) => ({name, type}))).toEqual([
      {name: '@bfra.me/.github', type: 'patch'},
      {name: 'renovate-changesets', type: 'patch'},
      {name: 'update-metadata', type: 'patch'},
      {name: 'update-repository-settings', type: 'patch'},
    ])
    expect(oracle.releasePlan.changesets).toHaveLength(4)
  })

  it('skips when the PR changeset is still present on disk', async () => {
    await fs.writeFile(
      path.join(workspace, '.changeset/existing-renovate-changesets.md'),
      `---\n'renovate-changesets': patch\n---\n\nRefresh pnpm lockfile dependencies\n\n**Multi-package update** for package \`renovate-changesets\`.\n`,
      'utf8',
    )
    octokitMocks.listFiles.mockResolvedValue({
      data: [
        {
          filename: '.changeset/existing-renovate-changesets.md',
          status: 'added',
          additions: 1,
          deletions: 0,
        },
      ],
    })

    await run()

    // Keep this strict so new skipped-output keys require a conscious test update.
    // An incomplete skip-path output set was a real defect in this action's history.
    expect(Object.fromEntries(contractState.outputs)).toEqual({
      'changesets-created': '0',
      'changeset-files': '[]',
      'update-type': '',
      dependencies: '[]',
      'changeset-summary': '',
      'multi-package-strategy': 'single',
      'workspace-packages-count': '0',
      'package-relationships-count': '0',
      'affected-packages': '[]',
      'multi-package-reasoning': '[]',
      'primary-category': '',
      'all-categories': '[]',
      'categorization-summary': '{}',
      'security-updates': '0',
      'breaking-changes': '0',
      'high-priority-updates': '0',
      'average-risk-level': '0',
      'categorization-confidence': 'low',
      'commit-success': 'false',
      'commit-sha': '',
      'committed-files': '[]',
      'git-error': '',
      'push-success': 'false',
      'push-error': '',
      'conflicts-resolved': 'false',
      'conflict-resolution': '',
      'branch-updated': 'false',
      'retry-attempts': '0',
      'pr-description-updated': 'false',
      'pr-description-error': '',
      'pr-comment-created': 'false',
      'pr-comment-error': '',
      'grouped-prs-enabled': 'false',
      'grouped-prs-found': '0',
      'grouped-prs-updated': '0',
      'grouped-prs-failed': '0',
      'grouped-pr-strategy': 'none',
      'grouped-pr-identifier': '',
      'grouped-pr-results': '[]',
    })
  })

  it('uses the root fallback when only the lockfile changes', async () => {
    octokitMocks.listFiles.mockResolvedValue({
      data: [{filename: 'pnpm-lock.yaml', status: 'modified', additions: 1, deletions: 1}],
    })

    await run()

    const oracle = await runChangesetsOracle('lockfile-maintenance-fallback', workspace, {
      errors: contractState.errors,
      warnings: contractState.warnings,
      outputs: contractState.outputs,
    })
    expect(authoredReleases(oracle.releasePlan).map(({name, type}) => ({name, type}))).toEqual([
      {name: '@bfra.me/.github', type: 'patch'},
    ])
    expect(effectiveReleases(oracle.releasePlan).map(({name, type}) => ({name, type}))).toEqual([
      {name: '@bfra.me/.github', type: 'patch'},
    ])
  })
})

function initializeGitRepository(directory: string): void {
  for (const args of [
    ['init', '-b', 'main'],
    ['add', '.'],
    [
      '-c',
      'user.name=contract-test',
      '-c',
      'user.email=contract-test@example.invalid',
      'commit',
      '-m',
      'fixture baseline',
    ],
  ]) {
    const result = spawnSync('git', args, {cwd: directory, encoding: 'utf8'})
    if (result.status !== 0) {
      throw new Error(
        `Failed to initialize fixture git repository: git ${args.join(' ')}\n${result.stderr}`,
      )
    }
  }
}
