# Continuous Integration jobs for changes headed to main.
---
name: Main

on:
  merge_group:
  pull_request:
    branches: [main]
    types: [opened, synchronize, ready_for_review, reopened]
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions:
  contents: read

jobs:
  quality-check:
    name: Quality Check
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Checkout Branch
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: 📦 Setup PNPM
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          run_install: false

      - name: 🏆 Setup Node.js
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          cache: pnpm
          node-version-file: .node-version

      - name: 🧰 Install dependencies
        env:
          HUSKY: '0'
        run: pnpm bootstrap

      - name: 💅🏽 Run Quality Checks
        run: pnpm quality-check

  release:
    if: github.repository == 'bfra-me/.github' &&  github.event_name == 'push' && github.ref =='refs/heads/main'
    name: Release
    needs: [quality-check]
    runs-on: ubuntu-latest
    steps:
      - id: get-workflow-access-token
        name: Get Workflow Access Token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          app-id: ${{ secrets.APPLICATION_ID }}
          private-key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
      - name: Setup Git user
        run: |
          git config --global user.email '118100583+bfra-me[bot]@users.noreply.github.com'
          git config --global user.name 'bfra-me[bot]'
      - name: Checkout repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: 0
          token: ${{ steps.get-workflow-access-token.outputs.token }}
      - name: Setup PNPM
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          run_install: false
      - name: Setup Node.js
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          cache: pnpm
          node-version-file: .node-version
      - name: Install dependencies
        env:
          HUSKY: '0'
        run: pnpm bootstrap
      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@a45c4d594aa4e2c509dc14a9f2b3b67ba3780d0d # v1.9.0
        with:
          commit: 'chore(changesets): publish release'
          createGithubReleases: false
          publish: pnpm release
          setupGitUser: false
          title: 'chore(🦋📦): publish release'
          version: pnpm bump
        env:
          GH_REPO: ${{ github.repository }}
          GITHUB_TOKEN: ${{ steps.get-workflow-access-token.outputs.token }}
