---
name: Create Renovate Changeset

on:
  merge_group:
  pull_request_target:

permissions:
  contents: read

jobs:
  create-changeset:
    name: Create Renovate Changeset
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    if: github.repository == 'bfra-me/.github' && ( github.actor == 'bfra-me[bot]' || github.actor == 'renovate[bot]' )
    steps:
      - id: get-workflow-access-token
        name: Get Workflow Access Token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        with:
          app-id: ${{ secrets.APPLICATION_ID }}
          private-key: ${{ secrets.APPLICATION_PRIVATE_KEY }}

      - name: Setup Git user
        run: |
          git config --global user.email '118100583+bfra-me[bot]@users.noreply.github.com'
          git config --global user.name 'bfra-me[bot]'

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 2
          ref: ${{ github.head_ref }}
          token: ${{ steps.get-workflow-access-token.outputs.token }}

      - name: 📦 Setup PNPM
        uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4.3.0
        with:
          run_install: false

      - name: 🏆 Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          cache: pnpm
          node-version-file: .node-version

      - name: 🧰 Install dependencies
        env:
          HUSKY: '0'
        run: pnpm bootstrap

      - id: renovate-changesets
        name: 🖌️ Generate Renovate changesets
        run: pnpx @scaleway/changesets-renovate
