---
name: Create Renovate Changeset

on:
  merge_group:
  pull_request_target:
  workflow_call:
    secrets:
      APPLICATION_ID:
        description: GitHub App ID for generating tokens
        required: true
      APPLICATION_PRIVATE_KEY:
        description: GitHub App private key for generating tokens
        required: true

permissions:
  contents: read

jobs:
  create-changeset:
    name: Create Renovate Changeset
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    if: >-
      (github.repository == 'bfra-me/.github' || github.event_name == 'workflow_call') &&
      (github.actor == 'bfra-me[bot]' || github.actor == 'renovate[bot]')
    steps:
      - id: get-workflow-access-token
        name: Get Workflow Access Token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        with:
          app-id: ${{ secrets.APPLICATION_ID }}
          private-key: ${{ secrets.APPLICATION_PRIVATE_KEY }}

      - name: Setup Git user
        run: |
          git config --global user.email '118100583+bfra-me[bot]@users.noreply.github.com'
          git config --global user.name 'bfra-me[bot]'

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 2
          ref: ${{ github.head_ref }}
          token: ${{ steps.get-workflow-access-token.outputs.token }}

      - id: renovate-changesets
        name: 🖌️ Generate Renovate changesets
        uses: bfra-me/.github/.github/actions/renovate-changesets@61be6f047e61e96548242b17177822692c16fca7 # renovate-changesets@0.2.15
        with:
          token: ${{ steps.get-workflow-access-token.outputs.token }}
          commit-back: 'true'
          max-retries: '3'
