# Update repository settings to match the definitions in .github/settings.yml.
---
name: Update Repo Settings

on:
  push:
    branches: [main]
  schedule:
    - cron: '55 2 * * *' # Every day at 02:55 UTC
  workflow_call:
    secrets:
      APPLICATION_ID:
        description: GitHub App ID
        required: true
      APPLICATION_PRIVATE_KEY:
        description: GitHub App private key
        required: true
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read

jobs:
  update-repo-settings:
    name: Update Repository Settings
    runs-on: ubuntu-latest
    steps:
      - if: github.event_name == 'push'
        name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - id: filter
        if: github.event_name == 'push'
        name: Filter Changed Files
        uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        with:
          filters: |
            changes:
              - 'common-settings.yaml'
              - '.github/settings.yml'
              - '.github/workflows/update-repo-settings.yaml'

      - id: get-workflow-access-token
        if: github.event_name != 'push' || steps.filter.outputs.changes == 'true'
        name: Get Workflow Access Token
        uses: actions/create-github-app-token@7bd03711494f032dfa3be3558f7dc8787b0be333 # v3.1.0
        with:
          app-id: ${{ secrets.APPLICATION_ID }}
          private-key: ${{ secrets.APPLICATION_PRIVATE_KEY }}

      - id: workflow-ref
        if: github.event_name != 'push' || steps.filter.outputs.changes == 'true'
        name: Resolve workflow ref
        run: echo "ref=${GITHUB_WORKFLOW_REF##*@}" >> "$GITHUB_OUTPUT"

      - if: github.event_name != 'push' || steps.filter.outputs.changes == 'true'
        name: Checkout action
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: bfra-me/.github
          ref: ${{ steps.workflow-ref.outputs.ref }}
          token: ${{ steps.get-workflow-access-token.outputs.token }}
          path: .bfra-me-github
          sparse-checkout: .github/actions/update-repository-settings

      - env:
          GITHUB_TOKEN: ${{ steps.get-workflow-access-token.outputs.token }}
        if: github.event_name != 'push' || steps.filter.outputs.changes == 'true'
        name: Update Repository Settings (${{ github.repository }})
        uses: ./.bfra-me-github/.github/actions/update-repository-settings
        with:
          token: ${{ steps.get-workflow-access-token.outputs.token }}
